development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: ab5408c7ef8ec79a12e2053ac12c85cbb2c2a1199628b8e1195ee73be9deb1a2faaab8ed4759a099bba0855ab5129a412f83b8df1aa2b1ea44317658920d3041

test:
  secret_key_base: ab5408c7ef8ec79a12e2053ac12c85cbb2c2a1199628b8e1195ee73be9deb1a2faaab8ed4759a099bba0855ab5129a412f83b8df1aa2b1ea44317658920d3041

production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
